spring:
  cloud:
    gateway:
      routes:
        - id: baidu
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: product_route
          uri: lb://market-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: third_route
          uri: lb://market-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: member_route
          uri: lb://market-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: member_ware
          uri: lb://market-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}

        - id: bigkel_host_route
          uri: lb://market-product
          predicates:
            - Host=bigkel.com

        - id: bigkel_search_route
          uri: lb://market-search
          predicates:
            - Host=search.bigkel.com
## 前端访问后端带上/api
## http://localhost:8989/api/captcha.jpg     http://localhost:8080/renren-fast/captcha.jpg
